# Generated by Django 6.0.5 on 2026-05-22 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PanelMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Время замера')),
                ('energy_production', models.FloatField(verbose_name='Выработка энергии (кВтч)')),
                ('temperature', models.FloatField(verbose_name='Температура (°C)')),
                ('irradiance', models.FloatField(verbose_name='Интенсивность излучения (Вт/м²)')),
                ('voltage', models.FloatField(blank=True, null=True, verbose_name='Напряжение (В)')),
                ('current', models.FloatField(blank=True, null=True, verbose_name='Ток (А)')),
            ],
            options={
                'verbose_name': 'Показатель панели',
                'verbose_name_plural': 'Показатели панелей',
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_value', models.FloatField(verbose_name='Предсказанное значение')),
                ('model_name', models.CharField(max_length=100, verbose_name='Использованная модель')),
                ('prediction_date', models.DateTimeField(auto_now_add=True)),
                ('metric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prediction', to='analytics.panelmetric')),
            ],
            options={
                'verbose_name': 'Предсказание',
                'verbose_name_plural': 'Предсказания',
            },
        ),
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название панели')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('capacity', models.FloatField(verbose_name='Мощность (Вт)')),
                ('installed_date', models.DateField(blank=True, null=True, verbose_name='Дата установки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Солнечная панель',
                'verbose_name_plural': 'Солнечные панели',
            },
        ),
        migrations.AddField(
            model_name='panelmetric',
            name='panel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='analytics.solarpanel'),
        ),
    ]
